version: '3.8'
services:

  postgres:
    image: 'postgres:13.1-alpine'
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=creditdb
  app:
    build:
      context: .
    ports:
    - 8085:8085
      